### ISSUE TITLE
Saved MSAL accounts leads to "No cached RefreshToken"

### ISSUE THREAD

**Issue by ItsTheSky** [CmlLib/CmlLib.Core.Auth.Microsoft#22]
Hi there!
I'm remaking my whole launcher cleaner now, but I face an issue. I use MSAL to log to accounts;
Once they are logged in, it works fine. However, when the launcher restarts, and I get JEGameAccount accounts via the `AccountManager`, the `ToLauncherSession` method returns an "invalidated" session (in-game I get the "invalid session" message), and using `LoginHandler.AuthenticateSilently` throws the following error:

```
Cached RefreshToken of the user was empty. Interactive Microsoft authentication is required.
   at XboxAuthNet.Game.OAuth.SilentMicrosoftOAuth.Authenticate(AuthenticateContext context, MicrosoftOAuthParameters parameters)
   at XboxAuthNet.Game.OAuth.MicrosoftOAuth.Authenticate(AuthenticateContext context)
   at XboxAuthNet.Game.Authenticators.SessionAuthenticator`1.ExecuteAsync(AuthenticateContext context)
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.doInnerAuth(Int32 index, AuthenticateContext context)
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.doInnerAuth(Int32 index, AuthenticateContext context)
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.doInnerAuth(Int32 index, AuthenticateContext context)
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.ExecuteAsync(AuthenticateContext context)
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.ExecuteAsync()
   at CmlLib.Core.Auth.Microsoft.Extensions.ExecuteForLauncherAsync(NestedAuthenticator self)
   at CmlLib.Core.Auth.Microsoft.JELoginHandler.AuthenticateSilently(IXboxGameAccount account, CancellationToken cancellationToken)
   at MinecraftLauncher.Models.GameAccount.<get_SelectAccountCommand>b__21_0() in B:\Sky\Projets\CSharp\Launchers\MinecraftLauncher\MinecraftLauncher\Models\GameAccount.cs:line 67
```

Here's my different code part (don't hesitate to let me know if any are missing to solve the issue better):

### LoginHandler creation & Accounts listing

```csharp
 LoginHandler = new JELoginHandlerBuilder()
     .WithAccountManager(Paths.BuildAppPath(["accounts.json"]))
     .WithHttpClient(Constants.HttpClient)
     .Build();
 List<GameAccount> accounts = new List<GameAccount>();
 foreach (var account in LoginHandler.AccountManager.GetAccounts())
 {
     if (account is not JEGameAccount gameAccount)
         continue;
     
     accounts.Add(new GameAccount { Account = gameAccount });
 }
```

### Authenticating ('_page' is the class above)

```csharp
var authenticator = _page.LoginHandler.CreateAuthenticatorWithNewAccount();
authenticator.AddMsalOAuth(_page.ClientApplication, msal => msal.Interactive());
authenticator.AddXboxAuthForJE(xbox => xbox.Basic());
authenticator.AddForceJEAuthenticator();
ISessionStorage session;
MainWindow.Instance.ViewModel.OverlayMessage = Translation.Get("MicrosoftAuthenticating");
try
{
    session = await authenticator.ExecuteAsync();
}
catch (Exception e)
{
    WindowUtils.ShowErrorBox(e.Message.Contains("NOT_FOUND")
        ? Translation.Get("MicrosoftAccountNotFound")
        : Translation.Get("MicrosoftAuthFailed", e.Message));
    return;
}
finally
{
    MainWindow.Instance.ViewModel.OverlayMessage = null;
}
var account = new GameAccount { Account = new JEGameAccount(session) };
Accounts.Add(account);
_page.LoginHandler.AccountManager.SaveAccounts();
```

### JEGameHandler to MSession (from class GameAccount)

```csharp
public async Task<MSession> GetSession(JELoginHandler loginHandler)
{
    if (_offlineUsername != null)
        return MSession.CreateOfflineSession(_offlineUsername);
    
    if (_account == null)
        throw new InvalidOperationException("Account is not loaded.");
    return await loginHandler.AuthenticateSilently(Account);
}
```

**Comment by AlphaBs** [comment]
if the account is authenticated with MSAL, the silent authentication also should be with MSAL.

Instead of `loginHandler.AuthenticateSilently`,

```csharp
var authenticator = loginHandler.CreateAuthenticator(Account);
authenticator.AddMsalOAuth(ClientApplication, msal => msal.Silent()); authenticator.AddXboxAuthForJE(xbox => xbox.Basic()); authenticator.AddJEAuthenticator();
return await authenticator.ExecuteForLauncherAsync();
```

https://alphabs.gitbook.io/cmllib/auth.microsoft/xboxauthnet.game.msal/oauth#silent

**Comment by ItsTheSky** [comment]
Seems to work fine now! Thanks for the help👍
