### ISSUE TITLE
Error. Help pls!

### ISSUE THREAD

**Issue by lingo000** [CmlLib/CmlLib.Core.Auth.Microsoft#23]
Select Authentication mode:
[1] Default
[2] Interactive (OAuth)
[3] Silent (OAuth)
[4] Interactive (Msal)
[5] Silent (Msal)
[6] DeviceCode (Msal)
[7] Signout without OAuth signout page
[8] Signout with OAuth signout page
[9] Show token informations

Number: 1
Start Authentication...
info: CmlLib.Core[749203]
      Start SilentMicrosoftOAuth
fail: CmlLib.Core[749401]
      Catch exception by FallbackAuthenticator
      XboxAuthNet.OAuth.MicrosoftOAuthException: Cached RefreshToken of the user was empty. Interactive Microsoft authentication is required.
         at XboxAuthNet.Game.OAuth.SilentMicrosoftOAuth.Authenticate(AuthenticateContext context, MicrosoftOAuthParameters parameters) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\SilentMicrosoftOAuth.cs:line 21
         at XboxAuthNet.Game.OAuth.MicrosoftOAuth.Authenticate(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\MicrosoftOAuth.cs:line 17
         at XboxAuthNet.Game.Authenticators.SessionAuthenticator`1.ExecuteAsync(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\SessionAuthenticator.cs:line 18
         at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 40
fail: CmlLib.Core[749401]
      Catch exception by FallbackAuthenticator
      XboxAuthNet.OAuth.MicrosoftOAuthException: LoginHint was empty.
         at XboxAuthNet.Game.OAuth.MicrosoftOAuthLoginHintValidator.Validate(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\MicrosoftOAuthLoginHintValidator.cs:line 23
         at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 37
info: CmlLib.Core[749202]
      Start InteractiveMicrosoftOAuth
fail: CmlLib.Core[749401]
      Catch exception by FallbackAuthenticator
      System.PlatformNotSupportedException: Current platform does not support to provide default WebUI.
         at XboxAuthNet.PlatformManager.CreateWebUI(WebUIOptions uiOptions)
         at XboxAuthNet.OAuth.CodeFlow.CodeFlowBuilder.createDefaultWebUIForPlatform()
         at XboxAuthNet.OAuth.CodeFlow.CodeFlowBuilder.Build()
         at XboxAuthNet.Game.OAuth.InteractiveMicrosoftOAuth.Authenticate(AuthenticateContext context, MicrosoftOAuthParameters parameters) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\InteractiveMicrosoftOAuth.cs:line 30
         at XboxAuthNet.Game.OAuth.MicrosoftOAuth.Authenticate(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\MicrosoftOAuth.cs:line 17
         at XboxAuthNet.Game.Authenticators.SessionAuthenticator`1.ExecuteAsync(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\SessionAuthenticator.cs:line 18
         at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 40
Unhandled exception. System.AggregateException: One or more errors occurred. (Current platform does not support to provide default WebUI.) (LoginHint was empty.) (Cached RefreshToken of the user was empty. Interactive Microsoft authentication is required.)
 ---> System.PlatformNotSupportedException: Current platform does not support to provide default WebUI.
   at XboxAuthNet.PlatformManager.CreateWebUI(WebUIOptions uiOptions)
   at XboxAuthNet.OAuth.CodeFlow.CodeFlowBuilder.createDefaultWebUIForPlatform()
   at XboxAuthNet.OAuth.CodeFlow.CodeFlowBuilder.Build()
   at XboxAuthNet.Game.OAuth.InteractiveMicrosoftOAuth.Authenticate(AuthenticateContext context, MicrosoftOAuthParameters parameters) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\InteractiveMicrosoftOAuth.cs:line 30
   at XboxAuthNet.Game.OAuth.MicrosoftOAuth.Authenticate(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\MicrosoftOAuth.cs:line 17
   at XboxAuthNet.Game.Authenticators.SessionAuthenticator`1.ExecuteAsync(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\SessionAuthenticator.cs:line 18
   at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 40
   --- End of inner exception stack trace ---
   at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 53
   at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.ExecuteAsync(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 19
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.doInnerAuth(Int32 index, AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\NestedAuthenticator.cs:line 34
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.doInnerAuth(Int32 index, AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\NestedAuthenticator.cs:line 33
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.doInnerAuth(Int32 index, AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\NestedAuthenticator.cs:line 33
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.ExecuteAsync(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\NestedAuthenticator.cs:line 19
   at XboxAuthNet.Game.Authenticators.NestedAuthenticator.ExecuteAsync() in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\NestedAuthenticator.cs:line 13
   at CmlLib.Core.Auth.Microsoft.Extensions.ExecuteForLauncherAsync(NestedAuthenticator self) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\CmlLib.Core.Auth.Microsoft\Extensions.cs:line 88
   at CmlLib.Core.Auth.Microsoft.JELoginHandler.Authenticate(IXboxGameAccount account, CancellationToken cancellationToken) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\CmlLib.Core.Auth.Microsoft\JELoginHandler.cs:line 39
   at Program.<Main>$(String[] args) in C:\Users\Andrey\Desktop\VS_FIGNIYA\examples\ConsoleTest\Program.cs:line 86
   at Program.<Main>(String[] args)
 ---> (Inner Exception #1) XboxAuthNet.OAuth.MicrosoftOAuthException: LoginHint was empty.
   at XboxAuthNet.Game.OAuth.MicrosoftOAuthLoginHintValidator.Validate(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\MicrosoftOAuthLoginHintValidator.cs:line 23
   at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 37<---

 ---> (Inner Exception #2) XboxAuthNet.OAuth.MicrosoftOAuthException: Cached RefreshToken of the user was empty. Interactive Microsoft authentication is required.
   at XboxAuthNet.Game.OAuth.SilentMicrosoftOAuth.Authenticate(AuthenticateContext context, MicrosoftOAuthParameters parameters) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\SilentMicrosoftOAuth.cs:line 21
   at XboxAuthNet.Game.OAuth.MicrosoftOAuth.Authenticate(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\OAuth\MicrosoftOAuth.cs:line 17
   at XboxAuthNet.Game.Authenticators.SessionAuthenticator`1.ExecuteAsync(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\SessionAuthenticator.cs:line 18
   at XboxAuthNet.Game.Authenticators.FallbackAuthenticator.tryAuth(AuthenticateContext context) in C:\Users\Andrey\Desktop\VS_FIGNIYA\src\XboxAuthNet.Game\Authenticators\FallbackAuthenticator.cs:line 40<---

**Comment by AlphaBs** [comment]
[1] Default [2] [3] are only available on Windows. you need to change TargetFramework to `net8-windows` in csproj file.
